# Правило для API (ПЕРВОЕ)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Правило для SPA (ВТОРОЕ)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200